#!/bin/bash
rm -rvf QR
mkdir -p QR
find * \( -name "*.mp4" -or -name "*.pdf" -or -name "*.jpg" \) -and -not -name "IMG*WA*.jpg" | while read f; do
    echo QR/`basename "$f" | sed 's/\....$/.png/'`
    qr "https://georgosch.github.io/heini-abschiedsgeschenk-18-20/$f" > QR/`basename "$f" | sed 's/\....$/.png/'`
done
